version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - andreasots
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: cargo
  directory: "/eris-macros"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
