[package]
name = "eris-macros"
version = "0.1.0"
authors = ["Andreas Ots <qrpth@qrpth.eu>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.2"
syn = "1.0.5"
proc-macro2 = "1.0.1"
