[package]
name = "eris-macros"
version = "0.1.0"
authors = ["Andreas Ots <qrpth@qrpth.eu>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.12"
syn = "0.15.34"
proc-macro2 = "0.4.30"
